-- --------------------------------------------------------
-- Διακομιστής:                  127.0.0.1
-- Έκδοση διακομιστή:            10.4.28-MariaDB - mariadb.org binary distribution
-- Λειτ. σύστημα διακομιστή:     Win64
-- HeidiSQL Έκδοση:              12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for πίνακας ludo.board
CREATE TABLE IF NOT EXISTS `board` (
  `x` tinyint(1) NOT NULL,
  `y` tinyint(1) NOT NULL,
  `b_color` enum('R','B','G','Y','W','RB','BG','GY','YR','RBGY','S','S_R','S_B','S_G','S_Y') NOT NULL,
  `b_fun` enum('R_sleep','B_sleep','G_sleep','Y_sleep','R_start','B_start','G_start','Y_start','W','S','R_final','B_final','G_final','Y_final') DEFAULT NULL,
  `p_color` enum('R','B','G','Y') DEFAULT NULL,
  `p_num` enum('1','2','3','4') DEFAULT NULL,
  PRIMARY KEY (`x`,`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table ludo.board: ~121 rows (approximately)
INSERT INTO `board` (`x`, `y`, `b_color`, `b_fun`, `p_color`, `p_num`) VALUES
	(1, 1, 'B', NULL, NULL, NULL),
	(1, 2, 'B', NULL, NULL, NULL),
	(1, 3, 'B', NULL, NULL, NULL),
	(1, 4, 'B', NULL, NULL, NULL),
	(1, 5, 'W', 'W', NULL, NULL),
	(1, 6, 'W', 'W', NULL, NULL),
	(1, 7, 'W', 'W', NULL, NULL),
	(1, 8, 'G', NULL, NULL, NULL),
	(1, 9, 'G', NULL, NULL, NULL),
	(1, 10, 'G', NULL, NULL, NULL),
	(1, 11, 'G', NULL, NULL, NULL),
	(2, 1, 'B', NULL, NULL, NULL),
	(2, 2, 'W', 'B_sleep', 'B', '1'),
	(2, 3, 'W', 'B_sleep', 'B', '2'),
	(2, 4, 'B', NULL, NULL, NULL),
	(2, 5, 'S', 'S', NULL, NULL),
	(2, 6, 'G', 'G_final', NULL, NULL),
	(2, 7, 'S_G', 'G_start', NULL, NULL),
	(2, 8, 'G', NULL, NULL, NULL),
	(2, 9, 'W', 'G_sleep', 'G', '1'),
	(2, 10, 'W', 'G_sleep', 'G', '2'),
	(2, 11, 'G', NULL, NULL, NULL),
	(3, 1, 'B', NULL, NULL, NULL),
	(3, 2, 'W', 'B_sleep', 'B', '3'),
	(3, 3, 'W', 'B_sleep', 'B', '4'),
	(3, 4, 'B', NULL, NULL, NULL),
	(3, 5, 'W', 'W', NULL, NULL),
	(3, 6, 'G', 'G_final', NULL, NULL),
	(3, 7, 'W', 'W', NULL, NULL),
	(3, 8, 'G', NULL, NULL, NULL),
	(3, 9, 'W', 'G_sleep', 'G', '3'),
	(3, 10, 'W', 'G_sleep', 'G', '4'),
	(3, 11, 'G', NULL, NULL, NULL),
	(4, 1, 'B', NULL, NULL, NULL),
	(4, 2, 'B', NULL, NULL, NULL),
	(4, 3, 'B', NULL, NULL, NULL),
	(4, 4, 'B', NULL, NULL, NULL),
	(4, 5, 'W', 'W', NULL, NULL),
	(4, 6, 'G', 'G_final', NULL, NULL),
	(4, 7, 'W', 'W', NULL, NULL),
	(4, 8, 'G', NULL, NULL, NULL),
	(4, 9, 'G', NULL, NULL, NULL),
	(4, 10, 'G', NULL, NULL, NULL),
	(4, 11, 'G', NULL, NULL, NULL),
	(5, 1, 'W', 'W', NULL, NULL),
	(5, 2, 'S_B', 'B_start', NULL, NULL),
	(5, 3, 'W', 'W', NULL, NULL),
	(5, 4, 'W', 'W', NULL, NULL),
	(5, 5, 'BG', NULL, NULL, NULL),
	(5, 6, 'G', 'G_final', NULL, NULL),
	(5, 7, 'GY', NULL, NULL, NULL),
	(5, 8, 'W', 'W', NULL, NULL),
	(5, 9, 'W', 'W', NULL, NULL),
	(5, 10, 'S', 'S', NULL, NULL),
	(5, 11, 'W', 'W', NULL, NULL),
	(6, 1, 'W', 'W', NULL, NULL),
	(6, 2, 'B', 'B_final', NULL, NULL),
	(6, 3, 'B', 'B_final', NULL, NULL),
	(6, 4, 'B', 'B_final', NULL, NULL),
	(6, 5, 'B', 'B_final', NULL, NULL),
	(6, 6, 'RBGY', NULL, NULL, NULL),
	(6, 7, 'Y', 'Y_final', NULL, NULL),
	(6, 8, 'Y', 'Y_final', NULL, NULL),
	(6, 9, 'Y', 'Y_final', NULL, NULL),
	(6, 10, 'Y', 'Y_final', NULL, NULL),
	(6, 11, 'W', 'W', NULL, NULL),
	(7, 1, 'W', 'W', NULL, NULL),
	(7, 2, 'S', 'S', NULL, NULL),
	(7, 3, 'W', 'W', NULL, NULL),
	(7, 4, 'W', 'W', NULL, NULL),
	(7, 5, 'RB', NULL, NULL, NULL),
	(7, 6, 'R', 'R_final', NULL, NULL),
	(7, 7, 'YR', NULL, NULL, NULL),
	(7, 8, 'W', 'W', NULL, NULL),
	(7, 9, 'W', 'W', NULL, NULL),
	(7, 10, 'S_Y', 'Y_start', NULL, NULL),
	(7, 11, 'W', 'W', NULL, NULL),
	(8, 1, 'R', NULL, NULL, NULL),
	(8, 2, 'R', NULL, NULL, NULL),
	(8, 3, 'R', NULL, NULL, NULL),
	(8, 4, 'R', NULL, NULL, NULL),
	(8, 5, 'W', 'W', NULL, NULL),
	(8, 6, 'R', 'R_final', NULL, NULL),
	(8, 7, 'W', 'W', NULL, NULL),
	(8, 8, 'Y', NULL, NULL, NULL),
	(8, 9, 'Y', NULL, NULL, NULL),
	(8, 10, 'Y', NULL, NULL, NULL),
	(8, 11, 'Y', NULL, NULL, NULL),
	(9, 1, 'R', NULL, NULL, NULL),
	(9, 2, 'W', 'R_sleep', 'R', '1'),
	(9, 3, 'W', 'R_sleep', 'R', '2'),
	(9, 4, 'R', NULL, NULL, NULL),
	(9, 5, 'W', 'W', NULL, NULL),
	(9, 6, 'R', 'R_final', NULL, NULL),
	(9, 7, 'W', 'W', NULL, NULL),
	(9, 8, 'Y', NULL, NULL, NULL),
	(9, 9, 'W', 'Y_sleep', 'Y', '1'),
	(9, 10, 'W', 'Y_sleep', 'Y', '2'),
	(9, 11, 'Y', NULL, NULL, NULL),
	(10, 1, 'R', NULL, NULL, NULL),
	(10, 2, 'W', 'R_sleep', 'R', '3'),
	(10, 3, 'W', 'R_sleep', 'R', '4'),
	(10, 4, 'R', NULL, NULL, NULL),
	(10, 5, 'S_R', 'R_start', NULL, NULL),
	(10, 6, 'R', 'R_final', NULL, NULL),
	(10, 7, 'S', 'S', NULL, NULL),
	(10, 8, 'Y', NULL, NULL, NULL),
	(10, 9, 'W', 'Y_sleep', 'Y', '3'),
	(10, 10, 'W', 'Y_sleep', 'Y', '4'),
	(10, 11, 'Y', NULL, NULL, NULL),
	(11, 1, 'R', NULL, NULL, NULL),
	(11, 2, 'R', NULL, NULL, NULL),
	(11, 3, 'R', NULL, NULL, NULL),
	(11, 4, 'R', NULL, NULL, NULL),
	(11, 5, 'W', 'W', NULL, NULL),
	(11, 6, 'W', 'W', NULL, NULL),
	(11, 7, 'W', 'W', NULL, NULL),
	(11, 8, 'Y', NULL, NULL, NULL),
	(11, 9, 'Y', NULL, NULL, NULL),
	(11, 10, 'Y', NULL, NULL, NULL),
	(11, 11, 'Y', NULL, NULL, NULL);

-- Dumping structure for πίνακας ludo.board_empty
CREATE TABLE IF NOT EXISTS `board_empty` (
  `x` tinyint(1) NOT NULL,
  `y` tinyint(1) NOT NULL,
  `b_color` enum('R','B','G','Y','W','RB','BG','GY','YR','RBGY','S','S_R','S_B','S_G','S_Y') NOT NULL,
  `b_fun` enum('R_sleep','B_sleep','G_sleep','Y_sleep','R_start','B_start','G_start','Y_start','W','S','R_final','B_final','G_final','Y_final') DEFAULT NULL,
  `p_color` enum('R','B','G','Y') DEFAULT NULL,
  `p_num` enum('1','2','3','4') DEFAULT NULL,
  PRIMARY KEY (`x`,`y`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table ludo.board_empty: ~121 rows (approximately)
INSERT INTO `board_empty` (`x`, `y`, `b_color`, `b_fun`, `p_color`, `p_num`) VALUES
	(1, 1, 'B', NULL, NULL, NULL),
	(1, 2, 'B', NULL, NULL, NULL),
	(1, 3, 'B', NULL, NULL, NULL),
	(1, 4, 'B', NULL, NULL, NULL),
	(1, 5, 'W', 'W', NULL, NULL),
	(1, 6, 'W', 'W', NULL, NULL),
	(1, 7, 'W', 'W', NULL, NULL),
	(1, 8, 'G', NULL, NULL, NULL),
	(1, 9, 'G', NULL, NULL, NULL),
	(1, 10, 'G', NULL, NULL, NULL),
	(1, 11, 'G', NULL, NULL, NULL),
	(2, 1, 'B', NULL, NULL, NULL),
	(2, 2, 'W', 'B_sleep', 'B', '1'),
	(2, 3, 'W', 'B_sleep', 'B', '2'),
	(2, 4, 'B', NULL, NULL, NULL),
	(2, 5, 'S', 'S', NULL, NULL),
	(2, 6, 'G', 'G_final', NULL, NULL),
	(2, 7, 'S_G', 'G_start', NULL, NULL),
	(2, 8, 'G', NULL, NULL, NULL),
	(2, 9, 'W', 'G_sleep', 'G', '1'),
	(2, 10, 'W', 'G_sleep', 'G', '2'),
	(2, 11, 'G', NULL, NULL, NULL),
	(3, 1, 'B', NULL, NULL, NULL),
	(3, 2, 'W', 'B_sleep', 'B', '3'),
	(3, 3, 'W', 'B_sleep', 'B', '4'),
	(3, 4, 'B', NULL, NULL, NULL),
	(3, 5, 'W', 'W', NULL, NULL),
	(3, 6, 'G', 'G_final', NULL, NULL),
	(3, 7, 'W', 'W', NULL, NULL),
	(3, 8, 'G', NULL, NULL, NULL),
	(3, 9, 'W', 'G_sleep', 'G', '3'),
	(3, 10, 'W', 'G_sleep', 'G', '4'),
	(3, 11, 'G', NULL, NULL, NULL),
	(4, 1, 'B', NULL, NULL, NULL),
	(4, 2, 'B', NULL, NULL, NULL),
	(4, 3, 'B', NULL, NULL, NULL),
	(4, 4, 'B', NULL, NULL, NULL),
	(4, 5, 'W', 'W', NULL, NULL),
	(4, 6, 'G', 'G_final', NULL, NULL),
	(4, 7, 'W', 'W', NULL, NULL),
	(4, 8, 'G', NULL, NULL, NULL),
	(4, 9, 'G', NULL, NULL, NULL),
	(4, 10, 'G', NULL, NULL, NULL),
	(4, 11, 'G', NULL, NULL, NULL),
	(5, 1, 'W', 'W', NULL, NULL),
	(5, 2, 'S_B', 'B_start', NULL, NULL),
	(5, 3, 'W', 'W', NULL, NULL),
	(5, 4, 'W', 'W', NULL, NULL),
	(5, 5, 'BG', NULL, NULL, NULL),
	(5, 6, 'G', 'G_final', NULL, NULL),
	(5, 7, 'GY', NULL, NULL, NULL),
	(5, 8, 'W', 'W', NULL, NULL),
	(5, 9, 'W', 'W', NULL, NULL),
	(5, 10, 'S', 'S', NULL, NULL),
	(5, 11, 'W', 'W', NULL, NULL),
	(6, 1, 'W', 'W', NULL, NULL),
	(6, 2, 'B', 'B_final', NULL, NULL),
	(6, 3, 'B', 'B_final', NULL, NULL),
	(6, 4, 'B', 'B_final', NULL, NULL),
	(6, 5, 'B', 'B_final', NULL, NULL),
	(6, 6, 'RBGY', NULL, NULL, NULL),
	(6, 7, 'Y', 'Y_final', NULL, NULL),
	(6, 8, 'Y', 'Y_final', NULL, NULL),
	(6, 9, 'Y', 'Y_final', NULL, NULL),
	(6, 10, 'Y', 'Y_final', NULL, NULL),
	(6, 11, 'W', 'W', NULL, NULL),
	(7, 1, 'W', 'W', NULL, NULL),
	(7, 2, 'S', 'S', NULL, NULL),
	(7, 3, 'W', 'W', NULL, NULL),
	(7, 4, 'W', 'W', NULL, NULL),
	(7, 5, 'RB', NULL, NULL, NULL),
	(7, 6, 'R', 'R_final', NULL, NULL),
	(7, 7, 'YR', NULL, NULL, NULL),
	(7, 8, 'W', 'W', NULL, NULL),
	(7, 9, 'W', 'W', NULL, NULL),
	(7, 10, 'S_Y', 'Y_start', NULL, NULL),
	(7, 11, 'W', 'W', NULL, NULL),
	(8, 1, 'R', NULL, NULL, NULL),
	(8, 2, 'R', NULL, NULL, NULL),
	(8, 3, 'R', NULL, NULL, NULL),
	(8, 4, 'R', NULL, NULL, NULL),
	(8, 5, 'W', 'W', NULL, NULL),
	(8, 6, 'R', 'R_final', NULL, NULL),
	(8, 7, 'W', 'W', NULL, NULL),
	(8, 8, 'Y', NULL, NULL, NULL),
	(8, 9, 'Y', NULL, NULL, NULL),
	(8, 10, 'Y', NULL, NULL, NULL),
	(8, 11, 'Y', NULL, NULL, NULL),
	(9, 1, 'R', NULL, NULL, NULL),
	(9, 2, 'W', 'R_sleep', 'R', '1'),
	(9, 3, 'W', 'R_sleep', 'R', '2'),
	(9, 4, 'R', NULL, NULL, NULL),
	(9, 5, 'W', 'W', NULL, NULL),
	(9, 6, 'R', 'R_final', NULL, NULL),
	(9, 7, 'W', 'W', NULL, NULL),
	(9, 8, 'Y', NULL, NULL, NULL),
	(9, 9, 'W', 'Y_sleep', 'Y', '1'),
	(9, 10, 'W', 'Y_sleep', 'Y', '2'),
	(9, 11, 'Y', NULL, NULL, NULL),
	(10, 1, 'R', NULL, NULL, NULL),
	(10, 2, 'W', 'R_sleep', 'R', '3'),
	(10, 3, 'W', 'R_sleep', 'R', '4'),
	(10, 4, 'R', NULL, NULL, NULL),
	(10, 5, 'S_R', 'R_start', NULL, NULL),
	(10, 6, 'R', 'R_final', NULL, NULL),
	(10, 7, 'S', 'S', NULL, NULL),
	(10, 8, 'Y', NULL, NULL, NULL),
	(10, 9, 'W', 'Y_sleep', 'Y', '3'),
	(10, 10, 'W', 'Y_sleep', 'Y', '4'),
	(10, 11, 'Y', NULL, NULL, NULL),
	(11, 1, 'R', NULL, NULL, NULL),
	(11, 2, 'R', NULL, NULL, NULL),
	(11, 3, 'R', NULL, NULL, NULL),
	(11, 4, 'R', NULL, NULL, NULL),
	(11, 5, 'W', 'W', NULL, NULL),
	(11, 6, 'W', 'W', NULL, NULL),
	(11, 7, 'W', 'W', NULL, NULL),
	(11, 8, 'Y', NULL, NULL, NULL),
	(11, 9, 'Y', NULL, NULL, NULL),
	(11, 10, 'Y', NULL, NULL, NULL),
	(11, 11, 'Y', NULL, NULL, NULL);

-- Dumping structure for πίνακας ludo.positions
CREATE TABLE IF NOT EXISTS `positions` (
  `x` tinyint(1) NOT NULL,
  `y` tinyint(1) NOT NULL,
  `pos` smallint(1) DEFAULT NULL,
  PRIMARY KEY (`x`,`y`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table ludo.positions: ~121 rows (approximately)
INSERT INTO `positions` (`x`, `y`, `pos`) VALUES
	(1, 1, NULL),
	(1, 2, NULL),
	(1, 3, NULL),
	(1, 4, NULL),
	(1, 5, 16),
	(1, 6, 17),
	(1, 7, 18),
	(1, 8, NULL),
	(1, 9, NULL),
	(1, 10, NULL),
	(1, 11, NULL),
	(2, 1, NULL),
	(2, 2, 200),
	(2, 3, 201),
	(2, 4, NULL),
	(2, 5, 15),
	(2, 6, 304),
	(2, 7, 19),
	(2, 8, NULL),
	(2, 9, 300),
	(2, 10, 301),
	(2, 11, NULL),
	(3, 1, NULL),
	(3, 2, 202),
	(3, 3, 203),
	(3, 4, NULL),
	(3, 5, 14),
	(3, 6, 305),
	(3, 7, 20),
	(3, 8, NULL),
	(3, 9, 302),
	(3, 10, 303),
	(3, 11, NULL),
	(4, 1, NULL),
	(4, 2, NULL),
	(4, 3, NULL),
	(4, 4, NULL),
	(4, 5, 13),
	(4, 6, 306),
	(4, 7, 21),
	(4, 8, NULL),
	(4, 9, NULL),
	(4, 10, NULL),
	(4, 11, NULL),
	(5, 1, 9),
	(5, 2, 10),
	(5, 3, 11),
	(5, 4, 12),
	(5, 5, NULL),
	(5, 6, 307),
	(5, 7, NULL),
	(5, 8, 22),
	(5, 9, 23),
	(5, 10, 24),
	(5, 11, 25),
	(6, 1, 8),
	(6, 2, 204),
	(6, 3, 205),
	(6, 4, 206),
	(6, 5, 207),
	(6, 6, NULL),
	(6, 7, 407),
	(6, 8, 406),
	(6, 9, 405),
	(6, 10, 404),
	(6, 11, 26),
	(7, 1, 7),
	(7, 2, 6),
	(7, 3, 5),
	(7, 4, 4),
	(7, 5, NULL),
	(7, 6, 107),
	(7, 7, NULL),
	(7, 8, 30),
	(7, 9, 29),
	(7, 10, 28),
	(7, 11, 27),
	(8, 1, NULL),
	(8, 2, NULL),
	(8, 3, NULL),
	(8, 4, NULL),
	(8, 5, 3),
	(8, 6, 106),
	(8, 7, 31),
	(8, 8, NULL),
	(8, 9, NULL),
	(8, 10, NULL),
	(8, 11, NULL),
	(9, 1, NULL),
	(9, 2, 100),
	(9, 3, 101),
	(9, 4, NULL),
	(9, 5, 2),
	(9, 6, 105),
	(9, 7, 32),
	(9, 8, NULL),
	(9, 9, 400),
	(9, 10, 401),
	(9, 11, NULL),
	(10, 1, NULL),
	(10, 2, 102),
	(10, 3, 103),
	(10, 4, NULL),
	(10, 5, 1),
	(10, 6, 104),
	(10, 7, 33),
	(10, 8, NULL),
	(10, 9, 402),
	(10, 10, 403),
	(10, 11, NULL),
	(11, 1, NULL),
	(11, 2, NULL),
	(11, 3, NULL),
	(11, 4, NULL),
	(11, 5, 36),
	(11, 6, 35),
	(11, 7, 34),
	(11, 8, NULL),
	(11, 9, NULL),
	(11, 10, NULL),
	(11, 11, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
